image: node:latest

cache:
  paths:
    - node_modules/
    - packages/sinuous-trace/node_modules
    - packages/sinuous-lifecycle/node_modules

pages:
  only:
    - publish
  script:
    - npm install

    - cd packages/sinuous-trace
    - npm install
    - npm run build
    - cd ..

    - cd packages/sinuous-lifecycle
    - npm install
    - npm run build
    - cd ..

    # Fix URL since GitLab hosts at a subdomain
    - sed -i 's|/web_modules/|/stayknit/web_modules/|' .babelrc.json
    - npm run setup

    - npm run ssr

    - mv serve public
  artifacts:
    paths:
      - public/
