image: node:latest

variables:
  GIT_SUBMODULE_STRATEGY: normal

cache:
  paths:
    - node_modules/
    - sinuous/node_modules/
    - sinuous/packages/sinuous/dist
    - sinuous/packages/sinuous/module

pages:
  only:
    - publish
  script:
    - npm install
    - cd sinuous
    - npm install
    - npm run build
    - cd ..
    # Fix URL since GitLab hosts at a subdomain
    - sed -i 's|/web_modules/|/stayknit/web_modules/|' .babelrc.json
    - npm run setup
    - mv serve public
  artifacts:
    paths:
      - public/
